### ISSUE TITLE
CUDA Backend maximum disparity bigger than 64

### ISSUE THREAD

**Issue by ghost** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#1]
Thank you for your great work! 
We have tested the package on CUDA backend and it works on maximum disparity 64 fine.
We tried to use 128 for maximum disparity but we got whole black disparity image. We have realised, that every number greater than 64 produces whole-black disparity image.

Best Regards

**Comment by hemalshahNV** [comment]
If this comes up in a later release, please reopen as needed.
