### ISSUE TITLE
Does Isaac ROS in this new version support Rational Polynomial calibration model?

### ISSUE THREAD

**Issue by FPSychotic** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#11]
I have a stereo camera that publish camera_info topic in rational polynomial intstead plumb_bob, is it supported in this new version?
If not, any idea how I could make it work? some node that make the conversion or maybe from a calibration file?, in the guide I could read "maybe you need calibrate your camera", but it don't say in what format, file type or where I need locate it.

Thanks by share

**Comment by hemalshahNV** [comment]
The Rectify node in the isaac_ros_image_proc package does support undistorting camera images with the rational polynomial distortion model. If CameraInfo specifies `sensor_msgs::distortion_models::RATIONAL_POLYNOMIAL`, Rectify will read the 8 distortion model parameters and apply (see here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline/blob/71f5b222751d593a6d2d18fa13781eb39acc8dc9/isaac_ros_image_proc/src/rectify_node.cpp#L281)
