### ISSUE TITLE
"invalid distortion type" error for rectify with plumb_bob distortion model

### ISSUE THREAD

**Issue by mnottale** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#27]
Hi there. Followed the camera calibration step here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docs/camera-calibration.md
It produces a yaml with "distortion_model: plumb_bob'.

When starting the april detection with usb cam launch file, I get this error:

    2023-04-07 14:54:43.711 ERROR /workspaces/isaac_ros-dev/isaac_ros_image_pipeline/isaac_ros_image_proc/gxf/tensorops/ImageUtils.cpp@113: invalid distortion type.
   2023-04-07 14:54:43.711 ERROR /workspaces/isaac_ros-dev/isaac_ros_image_pipeline/isaac_ros_image_proc/gxf/tensorops/TensorOperator.cpp@193: operation failed.

Is there anything I can do to fix that?

**Comment by jaiveersinghNV** [comment]
We are looking into this error as a possible regression. 

As a workaround, could you try manually editing the `distortion_model` field in your `camera_info.yaml` file to specify `rational_polynomial` instead of `plumb_bob`?

**Comment by mnottale** [comment]
That did the trick, thank you for the workaround.

**Comment by jaiveersinghNV** [comment]
As of [this commit](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline/commit/4b89cafac562ef436e9e9d6228e2d18aef18a924), we've now made a fix to support the `plumb_bob` model in `camera_info.yaml`. You should now be able to undo the workaround and still successfully launch the launch file.
