### ISSUE TITLE
build issue on 20.04 jetpack 5.1.1 negotiated package can't be found 

### ISSUE THREAD

**Issue by fxprime** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#31]
System information : 
NVIDIA NVIDIA Jetson Xavier NX Developer Kit
 L4T 35.3.1 [ JetPack UNKNOWN ]
   Ubuntu 20.04.6 LTS
   Kernel Version: 5.10.104-tegra
 CUDA 11.4.315
   CUDA Architecture: 7.2
 OpenCV version: 4.5.5
   OpenCV Cuda: YES
 CUDNN: 8.6.0.166
 TensorRT: 8.5.2.2
 Vision Works: NOT_INSTALLED
 VPI: 2.2.7
 Vulcan: 1.3.204
 ROS version : foxy (have tried using docker provided in isaac_common. Same issue)

Error : 
Starting >>> isaac_ros_nitros
--- stderr: isaac_ros_nitros                                
In file included from /home/fx/isaac_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/types/nitros_empty.hpp:21,
                 from /home/fx/isaac_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/types/nitros_empty.cpp:20:
/home/fx/isaac_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/types/nitros_format_agent.hpp:23:10: fatal error: negotiated/negotiated_publisher.hpp: No such file or directory
   23 | #include "negotiated/negotiated_publisher.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Thank you in advanced.

**Comment by jaiveersinghNV** [comment]
The `negotiated` package is prepared as part of our Isaac ROS Docker environment (see the Dockerfile [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.ros2_humble#L136)). If you're running inside the container we provide in the Isaac ROS Common repository and you've appropriately run `source /opt/ros/humble/setup.bash`, you shouldn't run into this issue.

Can you check if the `negotiated` package exists in your `/opt/ros/humble` directory inside the container?

Note that due to specific new features introduced in ROS 2 Humble, the Isaac ROS suite of packages is not compatible with ROS 2 Foxy or older versions.

**Comment by fxprime** [comment]
Thank you for you kind response. I manage to run on docker with 20.04. (i was tested on 18.04 but failed) 
So this issue can be closed.

**Comment by BADAL244** [comment]
--- stderr: isaac_ros_nitros                                          
In file included from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:84:2: error: #endif without #if
   84 | #endif  // ISAAC_ROS_NITROS__UTILS__VPI_UTILITIES_HPP_
      |  ^~~~~
In file included from /usr/local/cuda-11.4/include/cuda/std/cmath:19,
                 from /usr/local/cuda-11.4/include/cuda/std/complex:12,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/complex.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/tensor.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/local/cuda-11.4/include/cuda/std/detail/libcxx/include/cmath:569:101: error: ‘float cuda::std::__3::hypot(float, float, float)’ conflicts with a previous declaration
  569 | inline _LIBCUDACXX_INLINE_VISIBILITY float       hypot(       float x,       float y,       float z ) { return sqrt(x*x + y*y + z*z); }
      |                                                                                                     ^
In file included from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/emitter.h:10,
                 from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/yaml.h:11,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/parameter_parser.hpp:31,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/parameter.hpp:29,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/component.hpp:25,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/allocator.hpp:21,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:28,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/include/c++/9/cmath:1868:3: note: previous declaration ‘float std::hypot(float, float, float)’
 1868 |   hypot(float __x, float __y, float __z)
      |   ^~~~~
In file included from /usr/local/cuda-11.4/include/cuda/std/cmath:19,
                 from /usr/local/cuda-11.4/include/cuda/std/complex:12,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/complex.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/tensor.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/local/cuda-11.4/include/cuda/std/detail/libcxx/include/cmath:570:101: error: ‘double cuda::std::__3::hypot(double, double, double)’ conflicts with a previous declaration
  570 | inline _LIBCUDACXX_INLINE_VISIBILITY double      hypot(      double x,      double y,      double z ) { return sqrt(x*x + y*y + z*z); }
      |                                                                                                     ^
In file included from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/emitter.h:10,
                 from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/yaml.h:11,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/parameter_parser.hpp:31,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/parameter.hpp:29,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/component.hpp:25,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/allocator.hpp:21,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:28,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/include/c++/9/cmath:1872:3: note: previous declaration ‘double std::hypot(double, double, double)’
 1872 |   hypot(double __x, double __y, double __z)
      |   ^~~~~
In file included from /usr/local/cuda-11.4/include/cuda/std/cmath:19,
                 from /usr/local/cuda-11.4/include/cuda/std/complex:12,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/complex.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/tensor.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:30,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/local/cuda-11.4/include/cuda/std/detail/libcxx/include/cmath:572:101: error: ‘long double cuda::std::__3::hypot(long double, long double, long double)’ conflicts with a previous declaration
  572 | inline _LIBCUDACXX_INLINE_VISIBILITY long double hypot( long double x, long double y, long double z ) { return sqrt(x*x + y*y + z*z); }
      |                                                                                                     ^
In file included from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/emitter.h:10,
                 from /home/badal/vslam_ws/build/isaac_ros_nitros/_deps/yaml-cpp-src/include/yaml-cpp/yaml.h:11,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/parameter_parser.hpp:31,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/parameter.hpp:29,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/core/component.hpp:25,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/std/allocator.hpp:21,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_gxf/gxf/core/include/gxf/multimedia/video.hpp:28,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/include/isaac_ros_nitros/utils/vpi_utilities.hpp:23,
                 from /home/badal/vslam_ws/src/isaac_ros_nitros/isaac_ros_nitros/src/utils/vpi_utilities.cpp:11:
/usr/include/c++/9/cmath:1876:3: note: previous declaration ‘long double std::hypot(long double, long double, long double)’
 1876 |   hypot(long double __x, long double __y, long double __z)
      |   ^~~~~
make[2]: *** [CMakeFiles/isaac_ros_nitros.dir/build.make:188: CMakeFiles/isaac_ros_nitros.dir/src/utils/vpi_utilities.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/isaac_ros_nitros.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< isaac_ros_nitros [4min 14s, exited with code 2]

Summary: 9 packages finished [5min 20s]
  1 package failed: isaac_ros_nitros
  1 package had stderr output: isaac_ros_nitros
  15 packages not processed
