### ISSUE TITLE
Build errors due to YamlCPP

### ISSUE THREAD

**Issue by nakai-omer** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#34]
Hello,

Getting the following error during build:
```
/usr/bin/ld: /home/amram/development/nakai/packages/nakai-onboard/install/isaac_ros_stereo_image_proc/lib/libyaml-cpp.a(scanscalar.cpp.o): warning: relocation against `_ZZN4YAML3Exp5BlankEvE1e' in read-only section `.text'
/usr/bin/ld: /home/amram/development/nakai/packages/nakai-onboard/install/isaac_ros_stereo_image_proc/lib/libyaml-cpp.a(convert.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTIN4YAML11InvalidNodeE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by jaiveersinghNV** [comment]
Could you try clearing your `build/` and `install/` directories in the ROS workspace, and then rebuild?

It looks like you aren't using the Isaac ROS Docker container provided with accompanying development scripts in the [Isaac ROS Common](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common) repository. This Docker container bundles together all of the necessary dependencies for getting Isaac ROS and ROS 2 working on x86 and Jetson platforms, including `libyaml-cpp-dev`.

**Comment by nakai-omer** [comment]
@jaiveersinghNV I am using the docker image by dustynv:
`dustynv/ros:humble-ros-base-l4t-r35.3.1` 
Taken from: https://github.com/dusty-nv/jetson-containers/
