### ISSUE TITLE
Crash when fed too many distortion coefficients

### ISSUE THREAD

**Issue by QubitCube** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#35]
Hello,

I noticed when the rectify node subscribes to CameraInfo messages that have more than 12 distortion parameters, it crashes with a memory error after the first set of messages are received. In my case these last few distortion parameters were just 0 as I'm only using an 8-parameter model. I realise it probably doesn't support more than 12 (or 8?) parameters anyway, but thought i'd point it out.

It appears to happen during or after the nitros-type object destructor runs. It then crashes with either:

```
[component_container_mt-1] [DEBUG] [1691712994.727052095] [NitrosTypeBase]: [Destructor]Dstroying a Nitros-type object for handle = 155
[component_container_mt-1] free(): invalid next size (fast)
```

or:

```
[component_container_mt-1] [DEBUG] [1691716451.616054525] [NitrosTypeBase]: [Destructor]Dstroying a Nitros-typed object for handle = 128
[component_container_mt-1] free(): invalid pointer
```

Once I removed the trailing zeros in the distortion array, it worked fine.

**Comment by hemalshahNV** [comment]
That's an interesting yet disturbing find! Thank you for posting this. We'll look into this ASAP.
