### ISSUE TITLE
Build in ROS1 or out of ROS

### ISSUE THREAD

**Issue by JKWalleiee** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#36]
Hello,

I want to use these libraries, specifically the stereo image processing libraries, in ROS1 or in a normal application without ROS. Is it possible to do this? and what do i need to use these libraries in ROS1? Or use them without ROS?

I want to do this in a jetson Orin nano.

Thank you.

**Comment by gordongrigor** [comment]
Yes, you can use [VPI](https://docs.nvidia.com/vpi/) for stereo image processing directly from Jetpack in your application.  Isaac ROS stereo image proc provides an example of how to use the VPI API.
